### ISSUE TITLE
PTR records can collide

### ISSUE THREAD

**Issue by thockin** [kubernetes/dns#124]
As pointed out at the end of #25, it's possible to make PTR records collide with manual endpoints, in which case someone can hijack the PTR record, even across namespaces.

```
apiVersion: v1
kind: Service
metadata:
  name: manual-1
spec:
  clusterIP: None
  ports:
  - port: 80
```

```
apiVersion: v1
kind: Service
metadata:
  name: manual-2
spec:
  clusterIP: None
  ports:
  - port: 80
```

```
apiVersion: v1
kind: Endpoints
metadata:
  name: manual-1
subsets:
- addresses:
  - ip: 10.10.10.10
    hostname: foo
  ports:
  - port: 80
```

```
apiVersion: v1
kind: Endpoints
metadata:
  name: manual-2
subsets:
- addresses:
  - ip: 10.10.10.10
    hostname: bar
  ports:
  - port: 80
```

This sort of makes PTR records, as implemented, useless.  @sadlil offers #101, but I am worried about the impact of that when there are many DNS replicas.  I don't think it will fly, and we really really do not want DNS to watch Pods (some crazy people run DNS on every node, and it will CRUSH the apiserver).

There's also an issue of adding PTR records for IPs that are not pods, I will open a different issue.

We need to find a solution to this ASAP or revert #25 and eat some crow.

We need some authoritative place that can confirm IP->pod mapping, but that seems impossible to do without creating an O(num-pods) watch, or else trusting Endpoints to not hijack.
