### ISSUE TITLE
PTR records are created and served for non-cluster IPs

### ISSUE THREAD

**Issue by thockin** [kubernetes/dns#125]
```
apiVersion: v1
kind: Service
metadata:
  name: manual-1
spec:
  clusterIP: None
  ports:
  - port: 80
```

```
apiVersion: v1
kind: Endpoints
metadata:
  name: manual-1
subsets:
- addresses:
  - ip: 8.8.8.8
    hostname: foo
  ports:
  - port: 80
```

Reverse lookups for 8.8.8.8 now return `foo.manual-1.default.svc.cluster.local.`

We should probably never create reverse records except for service IPs and real pod IPs.
