### ISSUE TITLE
DNSMasq cache has low cache hit rate for some reason

### ISSUE THREAD

**Issue by felipejfc** [kubernetes/dns#160]
Hi, I'm running a k8s cluster in production with ~ 60 nodes, it has 870 pods on it.

Currently, 40 of these pods are kube-dns pods, each with 150m requests of CPU. (Yes, I had to scale it a lot)

I'm currently trying to figure out why I do need so much of them, one thing that I did today was to take a look at prometheus metrics exposed by the sidecar container and observed that:

![image](https://user-images.githubusercontent.com/285782/32076090-8c25fd48-ba7d-11e7-92a5-d0a3fa7e347c.png)

The ratio between hits/total number of requests is too low (around 21%), any hints on why it is too low? seeing dnsmasq requests it seems that some of the addresses it is resolving are never being cached for some reason.

just for reference, this is the number of requests that kubedns is receiving per minute (I guess)

![image](https://user-images.githubusercontent.com/285782/32076044-64673498-ba7d-11e7-8779-e4f30d29f46d.png)

**Comment by johnbelamaric** [comment]
A few questions:

 * Do you do a lot of queries to external resources (domains)?
 * Do you use FQDNs for your internal queries - for example "foo.namespace.svc.cluster.local" instead of just "foo"? If not, do you do a lot of cross-namespace lookups ("foo.ns2" from "ns1")?
 * Is negative caching (i.e., caching of `NXDOMAIN`) disabled in `dnsmasq`?

The way the client pod `resolv.conf` is set up, these things can lead to much higher query load. 
See https://github.com/kubernetes/kubernetes/issues/33554 for the engrossing details.

You could roll out CoreDNS (https://coredns.io) - see https://github.com/kubernetes/community/pull/1100 for some details on numbers there (as a maintainer of that I am biased of course). We also have an `auto path` function in CoreDNS that could make a difference, depending on your answers to the questions above. There are some weird edge cases with that though (I am still working on the blog to make those clear; I do believe they are very unlikely cases for the most part).

**Comment by felipejfc** [comment]
Hi @johnbelamaric 

- I do have a lot of queries to external resources (one thing I realised is that some of these queries are being cached (I can see [cached]... in dnsmasq logs) and some others are not)
- Usually I use only service.namespace instead of service.namespace.svc.cluster.local
- I guess no
```
      - args:
        - -v=2
        - -logtostderr
        - -configDir=/etc/k8s/dns/dnsmasq-nanny
        - -restartDnsmasq=true
        - --
        - -k
        - --cache-size=64000
        - --log-facility=-
        - --server=/cluster.local/127.0.0.1#10053
        - --server=/in-addr.arpa/127.0.0.1#10053
        - --server=/in6.arpa/127.0.0.1#10053
        image: gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.6
        name: dnsmasq
 ```
