### ISSUE TITLE
High latency for kube-dns 1.14.9 and 1.14.10

### ISSUE THREAD

**Issue by igorvpcleao** [kubernetes/dns#230]
Hi there, 
I noticed a high latency when I starting using _kube-dns_ `1.14.9` and `1.14.10`.

Images below show _kube-dns_ response time after upgrading _kube-dns_ from `1.14.6` to `1.14.10`

![screen shot 2018-05-09 at 15 13 57](https://user-images.githubusercontent.com/3065657/39832035-887dd036-539c-11e8-8872-eafbd3889a88.png)

![screen shot 2018-05-09 at 15 14 02](https://user-images.githubusercontent.com/3065657/39832037-8a438302-539c-11e8-845d-231769baf4a7.png)

Logs:

**kubectl logs kube-dns-7c8767566d-55jts -n kube-system -c kubedns**
I0509 18:24:33.037379       1 dns.go:48] version: 1.14.10
I0509 18:24:33.037981       1 server.go:69] Using configuration read from directory: /kube-dns-config with period 10s
I0509 18:24:33.038044       1 server.go:121] FLAG: --alsologtostderr="false"
I0509 18:24:33.038057       1 server.go:121] FLAG: --config-dir="/kube-dns-config"
I0509 18:24:33.038064       1 server.go:121] FLAG: --config-map=""
I0509 18:24:33.038083       1 server.go:121] FLAG: --config-map-namespace="kube-system"
I0509 18:24:33.038087       1 server.go:121] FLAG: --config-period="10s"
I0509 18:24:33.038109       1 server.go:121] FLAG: --dns-bind-address="0.0.0.0"
I0509 18:24:33.038113       1 server.go:121] FLAG: --dns-port="10053"
I0509 18:24:33.038132       1 server.go:121] FLAG: --domain="cluster.local."
I0509 18:24:33.038137       1 server.go:121] FLAG: --federations=""
I0509 18:24:33.038141       1 server.go:121] FLAG: --healthz-port="8081"
I0509 18:24:33.038145       1 server.go:121] FLAG: --initial-sync-timeout="1m0s"
I0509 18:24:33.038177       1 server.go:121] FLAG: --kube-master-url=""
I0509 18:24:33.038181       1 server.go:121] FLAG: --kubecfg-file=""
I0509 18:24:33.038206       1 server.go:121] FLAG: --log-backtrace-at=":0"
I0509 18:24:33.038221       1 server.go:121] FLAG: --log-dir=""
I0509 18:24:33.038229       1 server.go:121] FLAG: --log-flush-frequency="5s"
I0509 18:24:33.038233       1 server.go:121] FLAG: --logtostderr="true"
I0509 18:24:33.038245       1 server.go:121] FLAG: --nameservers=""
I0509 18:24:33.038253       1 server.go:121] FLAG: --stderrthreshold="2"
I0509 18:24:33.038256       1 server.go:121] FLAG: --v="2"
I0509 18:24:33.038269       1 server.go:121] FLAG: --version="false"
I0509 18:24:33.038283       1 server.go:121] FLAG: --vmodule=""
I0509 18:24:33.038491       1 server.go:169] Starting SkyDNS server (0.0.0.0:10053)
I0509 18:24:33.038715       1 server.go:179] Skydns metrics enabled (/metrics:10055)
I0509 18:24:33.038728       1 dns.go:188] Starting endpointsController
I0509 18:24:33.038732       1 dns.go:191] Starting serviceController
I0509 18:24:33.038777       1 dns.go:184] Configuration updated: {TypeMeta:{Kind: APIVersion:} Federations:map[] StubDomains:map[] UpstreamNameservers:[]}
I0509 18:24:33.038914       1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
I0509 18:24:33.038922       1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
I0509 18:24:33.538991       1 dns.go:222] Initialized services and endpoints from apiserver
I0509 18:24:33.539018       1 server.go:137] Setting up Healthz Handler (/readiness)
I0509 18:24:33.539030       1 server.go:142] Setting up cache handler (/cache)
I0509 18:24:33.539098       1 server.go:128] Status HTTP port 8081

**kubectl logs kube-dns-7c8767566d-55jts -n kube-system -c dnsmasq**
I0509 18:24:33.152179       1 main.go:74] opts: {{/usr/sbin/dnsmasq [-k --cache-size=1000 --neg-ttl=300 --min-cache-ttl=60 --max-cache-ttl=60 --local-ttl=60 --dns-forward-max=150 --log-facility=- --server=/cluster.local/127.0.0.1#10053 --server=/in-addr.arpa/127.0.0.1#10053 --server=/in6.arpa/127.0.0.1#10053] true} /etc/k8s/dns/dnsmasq-nanny 10000000000}
I0509 18:24:33.152263       1 nanny.go:94] Starting dnsmasq [-k --cache-size=1000 --neg-ttl=300 --min-cache-ttl=60 --max-cache-ttl=60 --local-ttl=60 --dns-forward-max=150 --log-facility=- --server=/cluster.local/127.0.0.1#10053 --server=/in-addr.arpa/127.0.0.1#10053 --server=/in6.arpa/127.0.0.1#10053]
I0509 18:24:33.242916       1 nanny.go:116] dnsmasq[10]: started, version 2.78 cachesize 1000
I0509 18:24:33.242992       1 nanny.go:116] dnsmasq[10]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect inotify
I0509 18:24:33.243005       1 nanny.go:116] dnsmasq[10]: using nameserver 127.0.0.1#10053 for domain in6.arpa
I0509 18:24:33.243008       1 nanny.go:116] dnsmasq[10]: using nameserver 127.0.0.1#10053 for domain in-addr.arpa
I0509 18:24:33.243012       1 nanny.go:116] dnsmasq[10]: using nameserver 127.0.0.1#10053 for domain cluster.local
I0509 18:24:33.243016       1 nanny.go:116] dnsmasq[10]: reading /etc/resolv.conf
I0509 18:24:33.243021       1 nanny.go:116] dnsmasq[10]: using nameserver 127.0.0.1#10053 for domain in6.arpa
I0509 18:24:33.243043       1 nanny.go:116] dnsmasq[10]: using nameserver 127.0.0.1#10053 for domain in-addr.arpa
I0509 18:24:33.243052       1 nanny.go:116] dnsmasq[10]: using nameserver 127.0.0.1#10053 for domain cluster.local
I0509 18:24:33.243055       1 nanny.go:116] dnsmasq[10]: using nameserver 172.22.0.2#53
I0509 18:24:33.243058       1 nanny.go:116] dnsmasq[10]: read /etc/hosts - 7 addresses
I0509 18:24:33.242916       1 nanny.go:119]
W0509 18:24:33.243067       1 nanny.go:120] Got EOF from stdout

**kubectl logs kube-dns-7c8767566d-55jts -n kube-system -c sidecar**
I0509 18:24:33.319908       1 main.go:51] Version v1.14.8.3
I0509 18:24:33.319944       1 server.go:45] Starting server (options {DnsMasqPort:53 DnsMasqAddr:127.0.0.1 DnsMasqPollIntervalMs:5000 Probes:[{Label:kubedns Server:127.0.0.1:10053 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:1} {Label:dnsmasq Server:127.0.0.1:53 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:1}] PrometheusAddr:0.0.0.0 PrometheusPort:10054 PrometheusPath:/metrics PrometheusNamespace:kubedns})
I0509 18:24:33.319970       1 dnsprobe.go:75] Starting dnsProbe {Label:kubedns Server:127.0.0.1:10053 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:1}
I0509 18:24:33.320035       1 dnsprobe.go:75] Starting dnsProbe {Label:dnsmasq Server:127.0.0.1:53 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:1}

Deployment:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-addon: kube-dns.addons.k8s.io
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
  name: kube-dns
  namespace: kube-system
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: kube-dns
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"CriticalAddonsOnly",
          "operator":"Exists"}]'
        service-discovery.datadoghq.com/sidecar.check_names: '["sidecar-check"]'
        service-discovery.datadoghq.com/sidecar.init_configs: '[{}]'
        service-discovery.datadoghq.com/sidecar.instances: '[[{"prometheus_endpoint":
          "http://%%host%%:10054/metrics"}]]'
      creationTimestamp: null
      labels:
        k8s-app: kube-dns
    spec:
      containers:
      - args:
        - --domain=cluster.local.
        - --dns-port=10053
        - --config-dir=/kube-dns-config
        - --v=2
        env:
        - name: PROMETHEUS_PORT
          value: "10055"
        image: gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.10
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthcheck/kubedns
            port: 10054
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: kubedns
        ports:
        - containerPort: 10053
          name: dns-local
          protocol: UDP
        - containerPort: 10053
          name: dns-tcp-local
          protocol: TCP
        - containerPort: 10055
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readiness
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            memory: 170Mi
          requests:
            cpu: 100m
            memory: 70Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /kube-dns-config
          name: kube-dns-config
      - args:
        - -v=2
        - -logtostderr
        - -configDir=/etc/k8s/dns/dnsmasq-nanny
        - -restartDnsmasq=true
        - --
        - -k
        - --cache-size=1000
        - --neg-ttl=300
        - --min-cache-ttl=60
        - --max-cache-ttl=60
        - --local-ttl=60
        - --dns-forward-max=150
        - --log-facility=-
        - --server=/cluster.local/127.0.0.1#10053
        - --server=/in-addr.arpa/127.0.0.1#10053
        - --server=/in6.arpa/127.0.0.1#10053
        image: gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.10
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthcheck/dnsmasq
            port: 10054
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: dnsmasq
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        resources:
          requests:
            cpu: 150m
            memory: 20Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/k8s/dns/dnsmasq-nanny
          name: kube-dns-config
      - args:
        - --v=2
        - --logtostderr
        - --probe=kubedns,127.0.0.1:10053,kubernetes.default.svc.cluster.local,5,A
        - --probe=dnsmasq,127.0.0.1:53,kubernetes.default.svc.cluster.local,5,A
        image: gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.10
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /metrics
            port: 10054
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: sidecar
        ports:
        - containerPort: 10054
          name: metrics
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: Default
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kube-dns
      serviceAccountName: kube-dns
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: kube-dns
          optional: true
        name: kube-dns-config
```
