### ISSUE TITLE
coreDNS deployment is not compatible with PodSecurityPolicy

### ISSUE THREAD

**Issue by fturib** [kubernetes/dns#254]
## IMPACT - Blocker

Right now this issue is blocking the PR "CoreDNS as "default" in kube-up deployment".
See several PR that have the same "pull-kubernetes-e2e-gce".

https://github.com/kubernetes/kubernetes/pull/67569
https://github.com/kubernetes/kubernetes/pull/66309
https://github.com/kubernetes/kubernetes/pull/62147

## Description

CoreDNS Deployment uses SecurityContext.
Basically this context tells  that CoreDNS needs admin privileges to be able to listen on port 53 (which is below 1024).

 ```
      securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - all
          readOnlyRootFilesystem: true
```

But when this deployment is running in a cluster that has PodSecurityPolicy enabled, the replicaSet is unable to create the CoreDNS Pods:

```
admin@francois-test-infra:~$ kubectl describe -n=kube-system replicasets coredns
Name:           coredns-77cd44d8df
Namespace:      kube-system
...
Conditions:
  Type             Status  Reason
  ----             ------  ------
  ReplicaFailure   True    FailedCreate
Events:
  Type     Reason        Age               From                   Message
  ----     ------        ----              ----                   -------
  Warning  FailedCreate  3m (x80 over 3h)  replicaset-controller  Error creating: pods "coredns-77cd44d8df-" is forbidden: unable to validate against any pod security policy: [spec.containers[0].securityContext.capabilities.add: Invalid value: "NET_BIND_SERVICE": capability may not be added]

```

## Actions to fix

Here we have two options:
### Abandon securityContext

and listen on port >= 1024. It needs adaptation of the Deployment and the Service. 
NOTE: It was so far expected to not change the service (from kube-dns definition) in order to allow upgrade without interruption of the DNS service.

### Ensure the right Security definition for CoreDNS.
Here we are not sure what needs to be done (under investigations)
Most likely, following other services that complies with PodSecurityPolicy, that would mean 
- create a "podsecuritypolicies" folder
- declare in that folder a manifest for a RoleBinding between coredns' ServiceAccount, and gce.privileged ClusterRole.

**RoleBinding to add in a dedicated podsecuritypolicies folder - will work for kube-up only:**
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gce:podsecuritypolicy:coredns
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/cluster-service: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gce:podsecuritypolicy:privileged
subjects:
- kind: ServiceAccount
  name: coredns
  namespace: kube-system
```

#### Questions 
- that would work for kube-up deployment, what about kubeadm ?
- why is that tied to GCE only ? 
- How do we deploy PSP in other platforms ?
