### ISSUE TITLE
node-cache is not working in some cases.

### ISSUE THREAD

**Issue by axot** [kubernetes/dns#318]
I found if a pod config with
-  dnsPolicy: ClusterFirstWithHostNet
-  hostNetwork: true

And then the DNS query will go to kube-dns directly instead of node-cache. Here is an example manifest what I tested.

```
apiVersion: v1
kind: Pod
metadata:
  name: bug-test
  namespace: default
spec:
  containers:
  - command:
    - sh
    - -c
    - |
      watch -n 1 nslookup google.com
    image: library/alpine
    name: bug-test
    resources:
      requests:
        cpu: 10m
        memory: 10Mi
  dnsPolicy: ClusterFirstWithHostNet
  hostNetwork: true
```
