### ISSUE TITLE
ndots:5 cause the long time name resolution

### ISSUE THREAD

**Issue by ehsanrocket** [kubernetes/dns#341]
Hi all
I deploy a kubernetes with CoreDNS 
on every pod , the resolve.conf file have `ndots:5 `entry that cause the name resolution takes too long or ends with bad address
how can I change this value to 0 in CoreDNS.

cat /etc/resolve.conf: 

```
nameserver 4.2.2.4
search default.svc.cluster.local svc.cluster.local cluster.local foo.com
options ndots:5
```

**Comment by chrisohaver** [comment]
> how can I change this value to 0 in CoreDNS.

The contents of resolv.conf is not controlled by CoreDNS.  It's copied to the pods by kubelet, based on the Pod's dns policy.

I think you can set a dnsConfig on Pods to override the ndots settings.  There may also be a way to alter the clusterFirst dnsPolicy (the default that pod's use) with a custom ndots.

Note however, that many applications rely on short name address resolution, and setting ndots to zero would break that.

**Comment by ehsanrocket** [comment]
thank you @chrisohaver 
I have appended these lines to my pod's yaml file: 
```
 dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 4.2.2.4
        searches:
          - default.svc.cluster.local
          - svc.cluster.local
          - cluster.local
        options:
          - name: ndots
            value: "1"
          - name: edns0
```
and now it works correctly
