### ISSUE TITLE
TIME-WAIT connections :8080

### ISSUE THREAD

**Issue by igorvpcleao** [kubernetes/dns#381]
Hi,

I've noticed relatively high number of connections in a TIME-WAIT state targeting `node-dns` (I believe they're for its health route). It's awkward that the number of `node-dns` connections in this state is greater than all other TIME-WAIT connections we have. Am I analysing it badly? Wondering if this may be a bug. 

```
ss --numeric --tcp state connected

State                  Recv-Q               Send-Q                              Local Address:Port                                Peer Address:Port
TIME-WAIT              0                    0                                   169.254.20.10:48814                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:48320                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49524                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:48014                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49352                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49334                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:48282                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49702                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:50000                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49830                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:48996                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49938                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49056                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49716                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49870                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49436                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49116                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49982                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:47902                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49642                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:48418                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:48632                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49290                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49804                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:50108                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:48888                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:50126                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49850                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49786                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49628                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49192                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:48718                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49610                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:48758                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:47820                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49738                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:50066                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49668                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:48364                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:48226                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:48572                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:48534                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49158                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49400                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:48940                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49254                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:50178                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49964                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:47954                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49484                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49316                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:50092                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49564                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:47736                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:48164                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:50038                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49378                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49456                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:50154                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:48076                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49900                              169.254.20.10:8080
TIME-WAIT              0                    0                                   169.254.20.10:49586                              169.254.20.10:8080
```

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  generation: 2
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: node-local-dns
    kubernetes.io/cluster-service: "true"
  name: node-local-dns
  namespace: kube-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: node-local-dns
  template:
    metadata:
      annotations:
        prometheus.io/port: "9253"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        k8s-app: node-local-dns
    spec:
      containers:
      - args:
        - -localip
        - 169.254.20.10,172.20.0.10
        - -conf
        - /etc/Corefile
        - -upstreamsvc
        - kube-dns-upstream
        image: k8s.gcr.io/k8s-dns-node-cache:1.15.13
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            host: 169.254.20.10
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: node-cache
        ports:
        - containerPort: 53
          hostPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          hostPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 9253
          hostPort: 9253
          name: metrics
          protocol: TCP
        resources:
          requests:
            cpu: 25m
            memory: 5Mi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /run/xtables.lock
          name: xtables-lock
        - mountPath: /etc/coredns
          name: config-volume
        - mountPath: /etc/kube-dns
          name: kube-dns-config
      dnsPolicy: Default
      hostNetwork: true
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: node-local-dns
      serviceAccountName: node-local-dns
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      volumes:
      - hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
        name: xtables-lock
      - configMap:
          defaultMode: 420
          name: kube-dns
          optional: true
        name: kube-dns-config
      - configMap:
          defaultMode: 420
          items:
          - key: Corefile
            path: Corefile.base
          name: node-local-dns
        name: config-volume
  templateGeneration: 2
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10%
    type: RollingUpdate
```
`node-dns` running on top of EKS with Kubernetes 1.15.11.

**Comment by prameshj** [comment]
I suspect these are connections from kubelet to the node-local-dns endpoint as part of livenessProbes. These should happen once in 10s... are there any other TIME_WAIT connections, excluding the node-local-dns ones?

**Comment by prameshj** [comment]
We skip connection tracking for healthcheck connections so they don't take up entries in conntrack table - https://github.com/kubernetes/dns/blob/cefee85aafbf57eb6eae590007bddb3f1b9c3e8d/cmd/node-cache/app/cache_app.go#L112, it could be a side effect of that.

**Comment by igorvpcleao** [comment]
> I suspect these are connections from kubelet to the node-local-dns endpoint as part of livenessProbes. These should happen once in 10s... are there any other TIME_WAIT connections, excluding the node-local-dns ones?

Gotcha. Yeah, I also think this is what's going on. Regarding TIME_WAIT connections, overall there's just a few others from applications related traffic.

**Comment by igorvpcleao** [comment]
> We skip connection tracking for healthcheck connections so they don't take up entries in conntrack table -
> 
> https://github.com/kubernetes/dns/blob/cefee85aafbf57eb6eae590007bddb3f1b9c3e8d/cmd/node-cache/app/cache_app.go#L112
> 
> , it could be a side effect of that.

I see. Ok. I don't think that by having this number of TIME_WAIT connections per node will cause us any harm, I was just concerned about the root cause ending up being something more problematic than this. If you're ok, I'll close this issue.

I really appreciate your time on this.

**Comment by igorvpcleao** [comment]
Hi @giannisbetas,

For the original post I believe this is indeed what prameshj replied. 
On the other hand, by looking at your message, it seems the requests you captured target `169.254.20.10:8080/` instead of `169.254.20.10:8080/health` (which is the route used by the liveness probe. I'd expect `/` to indeed return 404).
Are you sure you have
```
livenessProbe:
          failureThreshold: 3
          httpGet:
            host: 169.254.20.10
            path: /health
            port: 8080
            scheme: HTTP
```
with `path: /health` in your nodelocaldns yaml? https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/nodelocaldns/nodelocaldns.yaml#L162

If this `/health` route is properly set, such requests you captured are probably not related to this issue.
