### ISSUE TITLE
kube-dns does not watch endpointslices for hostnames to resolve

### ISSUE THREAD

**Issue by AaronFriel** [kubernetes/dns#504]
# Problem

Creating an endpoint slice and service in a cluster relying upon kube-dns results in no DNS resolution for either the service name or the hostnames under it.

## Steps to reproduce

Apply this simple endpoint slice and service with `kubectl apply -f`:

```yaml
# endpointslice-test.yaml
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  labels:
    endpointslice.kubernetes.io/managed-by: friel
    kubernetes.io/service-name: global
  name: global-endpoint-slice-test
  namespace: default
addressType: IPv4
endpoints:
- addresses:
  - 10.0.0.1
  conditions:
    ready: true
    serving: true
  hostname: node-0
- addresses:
  - 10.0.0.2
  conditions:
    ready: true
    serving: true
  hostname: node-1
ports: []
---
apiVersion: v1
kind: Service
metadata:
  labels:
    endpointslice.kubernetes.io/skip-mirror: "true"
  name: global
  namespace: default
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  publishNotReadyAddresses: true
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

Launch a container such as `alpine:latest` which contains an `nslookup` or similar, via:

```
$ kubectl -n default run "test-$RANDOM" -it --rm --image alpine:latest
If you don't see a command prompt, try pressing enter.
/ # nslookup global.default.svc.cluster.local
Server:         10.124.0.10
Address:        10.124.0.10:53

** server can't find global.default.svc.cluster.local: NXDOMAIN

** server can't find global.default.svc.cluster.local: NXDOMAIN
/ # # likewise for node-0.global.default.svc.cluster.local
/ # # likewise for node-1.global.default.svc.cluster.local
```

## Expected behavior:

In a cluster running coredns, endpointslices are discovered and resolved. Here's the output of a cluster running coredns:

```
/ # nslookup global.default.svc.cluster.local
Server:         10.0.0.10
Address:        10.0.0.10:53

Name:   global.default.svc.cluster.local
Address: 10.0.0.1
Name:   global.default.svc.cluster.local
Address: 10.0.0.2
/ #
/ # nslookup node-0.global.default.svc.cluster.local
Server:         10.0.0.10
Address:        10.0.0.10:53


Name:   node-0.global.default.svc.cluster.local
Address: 10.0.0.1
/ #
/ # nslookup node-1.global.default.svc.cluster.local
Server:         10.0.0.10
Address:        10.0.0.10:53


Name:   node-1.global.default.svc.cluster.local
Address: 10.0.0.2
```
