### ISSUE TITLE
`node-local-dns` requires extra validations for `kube-dns` configmap

### ISSUE THREAD

**Issue by tangenti** [kubernetes/dns#539]
`node-local-dns` loads the values of `stubDomains` and `upstreamNameservers` from `kube-dns` configmap and compiles the config into a Corefile. However, a valid `kube-dns` config may be compiled into an invalid Corefile.

For example, the following config would be considered as valid `kube-dns` config.
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
        {"example.com" : ["cluster.local"]}
  upstreamNameservers: |
        ["8.8.4.4"]
```

The name servers specified in the `stubDomains` fields will then be used as name servers for the plugin `forward` in the compiled Corefile. However, `forward` does not support FQDNs for the name servers, and it crashes when it sees such a configuration, and the container falls into a crash loop. Therefore we will need extra validations to make sure the values are valid for the `forward` plugin.
