### ISSUE TITLE
kube-dns doesn't expose service scoped dns names for pod IPs

### ISSUE THREAD

**Issue by pmalek** [kubernetes/dns#633]
### Problem statement

As described in https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#a-aaaa-records-1:

> Any Pods exposed by a Service have the following DNS resolution available:
> `pod-ipv4-address.service-name.my-namespace.svc.cluster-domain.example`

This is not the case for `kube-dns`. We're using (generating) those dns names from `EndpointSlice`s for inter cluster communication between services. It does work with coredns.

This is relevant for a number of users since GKE by default uses kube-dns.

Usage of service scoped dns names is preferred because it allows for wildcard certificates like `*.service-name.my-namespace.svc.cluster-domain.example` to be used.

### Proposed solution

Serve service scoped dns names.

**Comment by Michcioperz** [comment]
Seems like a bug in the documentation, as according to the [DNS specification](https://github.com/kubernetes/dns/blob/master/docs/specification.md) mentioned in the section linked in the issue, section 2.4.1, it's only provided for headless services (`clusterIP: None`) and with pod hostnames rather than IP addresses as the subdomain.

**Comment by davidxia** [comment]
As @Michcioperz brought up, I wonder if kube-dns is supposed to provide these A records or if it's a bug in the docs. Perhaps a maintainer can comment if kube-dns will ever provide this functionality?

In the meantime, I made a [PR to update the docs](https://github.com/kubernetes/website/pull/49532).

**Comment by programmer04** [comment]
I'm in favor of changing the behavior to fulfill what OP described, because 
- CoreDNS that is popular does it
- [GKE Autopilot](https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview) uses [Cloud DNS](https://cloud.google.com/kubernetes-engine/docs/concepts/service-discovery#cloud_dns) which also behaves the same as CoreDNS 

thus we're currently in Hyrum's Law to expect this behavior from the K8s cluster as a whole (no matter the underlying DNS and official specs, etc.)

**Comment by programmer04** [comment]
I made tests and support for the availability of DNS resolution like e.g. `10-96-2-4.example-service.default.svc` for `Pod`s exposed by a `Service` depends on a DNS provider and it looks like that 

|             | Cloud DNS     | Core DNS      |  kube-dns     |
|-------------| ------------- | ------------- | ------------- |
|**ClusterIP**   | ❌  | ✔️  |       ❌        |
| **Headless**     | ✔️  | ✔️  |      ❌         |

tested with the below configuration


```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  labels:
    app: example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
        - name: example-container
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  clusterIP: None
  selector:
    app: example-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
```
